### ISSUE TITLE
When adding powerline_gitstatus.gitstatus to the theme, the right segment is not shown anymore

### ISSUE THREAD

**Issue by florisvanwoudenberg** [jaspernbrouwer/powerline-gitstatus#11]
I tried installing this submodule, on OSX 10.11.
Using iTerm2 and ZSH.
Installed as explained, but when I add this to .config/powerline/themes/shell/default.json, the whole right segment is nog shown anymore. I checked, the json is valid.
Any idea?
{
    "function": "powerline_gitstatus.gitstatus",
    "priority": 40
}

**Comment by florisvanwoudenberg** [comment]
Apparently I had to remove the default function that displays the branch, after this all worked.
On OSX this was a problem, while on Ubuntu the branch was shown twice if the default was nog removed.

**Comment by jaspernbrouwer** [comment]
Glad you could resolve your immediate issue!

> the default function that displays the branch

You mean the "brach" segment that comes with Powerline itself? In theory this segment shouldn't be affected by other segments. If you like me to look at it, it would help if you could enable debug level logging to see where "powerline_gitstatus" fails.
