### ISSUE TITLE
Which folder for gitstatus

### ISSUE THREAD

**Issue by gbomacfly** [jaspernbrouwer/powerline-gitstatus#22]
Hello,

I want to install gitstatus, but it doesn't work for me.
I placed the folder in /usr/lib/python2.7/dist-packages/powerline/segments
Is this the correct folder?

**Comment by jcharaoui** [comment]
No, that won't work. This folder is for software installed via your package manager (eg. apt).

Just run `apt install powerline-gitstatus` and your package manager will take care of putting all the files in the correct places.
