### ISSUE TITLE
Pass the torch

### ISSUE THREAD

**Issue by jcharaoui** [jaspernbrouwer/powerline-gitstatus#24]
The last commit in this project happened over two years ago, and several pull request have been pending for months.

@jaspernbrouwer Are you still interested in maintaining this project? If not, would you be willing to consider allowing commit access to other contributors?

Thanks!

**Comment by jaspernbrouwer** [comment]
Hi there!

My personal life has consumed most of my time the last couple of years, and I expect it to continue doing so for a while :wink: 

So yes, it's time to pass the torch on!

I guess the question now is: to who'm?

**Comment by jcharaoui** [comment]
Thanks for taking the time to reply. I'd be willing to help on this front, as I recently decided to take up packaging powerline-gitstatus in Debian. But I don't want to step on anyone's toes and I'd welcome other contributors to join the effort.

**Comment by tyll** [comment]
It would be great if @jcharaoui could keep this project alive.

**Comment by jcharaoui** [comment]
Juste FTR, I'll be AFK for the next few weeks, but it's my intention to review some PRs when I return.

@jaspernbrouwer Would your prefer the project move into a new namespace or stay in yours?

**Comment by jaspernbrouwer** [comment]
Hey @jcharaoui!

I've added you as collaborator to this repo. I'll probably also need to add/transfer the package at PyPI. Do you have an account?

> Would your prefer the project move into a new namespace or stay in yours?

I'd like to keep it here for the moment, to see where this is going :slightly_smiling_face: Or perhaps move it into a new organization, where it's easier to manage maintainers and collaborators.

PS: Feel free to add your name to the license, as long as you keep mine in there :grin:

**Comment by jcharaoui** [comment]
> I've added you as collaborator to this repo. I'll probably also need to add/transfer the package at PyPI. Do you have an account?

I just created an account: https://pypi.org/user/lavamind/

> > Would your prefer the project move into a new namespace or stay in yours?
> 
> I'd like to keep it here for the moment, to see where this is going  Or perhaps move it into a new organization, where it's easier to manage maintainers and collaborators.

That's fine with me.

> PS: Feel free to add your name to the license, as long as you keep mine in there

Sure thing.

**Comment by jcharaoui** [comment]
Closing in the wake of a new version released on PyPI.
