### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by jcharaoui** [jaspernbrouwer/powerline-gitstatus#28]
Following all the testing & merging, I'd be ready to tag and release `v1.3.0`.

@jaspernbrouwer, do you have any objections?

**Comment by jaspernbrouwer** [comment]
Nope, go ahead!

Do you need me to release it at PyPI?

**Comment by jaspernbrouwer** [comment]
>Do you need me to release it at PyPI?

I've added you as maintainer at PyPI, so you should be able to release yourself :slightly_smiling_face:

**Comment by jcharaoui** [comment]
Release tagged and uploaded, thanks!
