### ISSUE TITLE
Also show in subdir of working dir

### ISSUE THREAD

**Issue by lastorset** [jaspernbrouwer/powerline-gitstatus#4]
Powerline's built-in VCS segment also works in subdirectories of the working directory. Perhaps powerline-gitstatus also could (optionally) do this.

**Comment by jaspernbrouwer** [comment]
Ah! I suspect this broke in the last version. I'll fix it as soon as possible!

**Comment by jaspernbrouwer** [comment]
Fixed in [v1.0.4](https://github.com/jaspernbrouwer/powerline-gitstatus/releases/tag/v1.0.4)!

**Comment by lastorset** [comment]
Sweet!

**Comment by jaspernbrouwer** [comment]
@lastorset: Sorry guys! I've messed up a bit with these working directory issues (#1 and #4) :(

There's a new release ([v1.1.0](https://github.com/jaspernbrouwer/powerline-gitstatus/releases/tag/v1.1.0)) that should fix them once and for all!

**Comment by lastorset** [comment]
Good, I was actually wondering about the powerline-daemon, but you seem to have read my mind! :)
