### ISSUE TITLE
How to Setup Terminal

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [jaspernbrouwer/powerline-gitstatus#5]
Hi, I'm trying to get this working. I installed Powerline and am using Bash. I got the default vcs segment working then swapped in powerline_gitstatus.gitstatus for it and it's not working.

Do I have to add something in my .profile or something?

**Comment by jaspernbrouwer** [comment]
When you have Powerline itself working, you don't need to do anything outside of the Powerline configuration. Everything is in the [readme](https://github.com/jaspernbrouwer/powerline-gitstatus/blob/master/README.md) really.

One thing I can think of is that the highlight groups this segment uses aren't defined. That would make the segment fail (not show up).

Also check if you've edited the correct color-scheme and theme, those that match your `~/.config/powerline/config.json`.

Otherwise, please enable the Powerline log and see if it contains a hint.

**Comment by jaspernbrouwer** [comment]
Also, run `powerline-lint`. If everything is ok, it doesn't produce output. So if you do get output, fix those issues, or report back to me if they are related to this segment.

**Comment by TimeTravelersHackedMe** [comment]
Looks like it has something to do with my color scheme. This is what powerline-lint generates:

```
Path /usr/local/lib/python2.7/site-packages/powerline/config_files/colorschemes/.DS_Store is not a directory or configuration file

Path /usr/local/lib/python2.7/site-packages/powerline/config_files/colorschemes/shell/.DS_Store is not a configuration file

Path /usr/local/lib/python2.7/site-packages/powerline/config_files/themes/.DS_Store is not a directory or configuration file

Path /usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/.DS_Store is not a configuration file

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_branch_detached) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_branch_detached not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_branch_dirty) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_branch_dirty not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_branch_clean) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_branch_clean not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_branch) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_branch not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_behind) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_behind not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_ahead) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_ahead not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_staged) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_staged not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_unmerged) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_unmerged not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_changed) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_changed not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_untracked) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_untracked not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus_stashed) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus_stashed not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus not defined in the following colorschemes: solarized

Error while checking theme (key /segments/left/list item 3/function)
found highlight groups list (gitstatus:divider) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/local/lib/python2.7/site-packages/powerline/config_files/themes/shell/default_leftonly.json", line 13, column 46:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 3/function)
found highlight group gitstatus:divider not defined in the following colorschemes: solarized
```

**Comment by jaspernbrouwer** [comment]
Looks like my segment is used in the shell theme `default_leftonly` and some (or all) highlight groups from my segment are not present in the color-scheme `solarized`.

If you're not using the color-scheme `solarized`, this is not the source of you issue. In any case, you can add this to the `groups` section of `.config/powerline/colorschemes/solarized.json`:

``` json
"gitstatus":                 { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] },
"gitstatus_branch":          { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] },
"gitstatus_branch_clean":    { "fg": "solarized:green",   "bg": "solarized:base02", "attrs": [] },
"gitstatus_branch_dirty":    { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] },
"gitstatus_branch_detached": { "fg": "solarized:magenta", "bg": "solarized:base02", "attrs": [] },
"gitstatus_behind":          { "fg": "solarized:base2",   "bg": "solarized:base02", "attrs": [] },
"gitstatus_ahead":           { "fg": "solarized:base2",   "bg": "solarized:base02", "attrs": [] },
"gitstatus_staged":          { "fg": "solarized:green",   "bg": "solarized:base02", "attrs": [] },
"gitstatus_unmerged":        { "fg": "solarized:red",     "bg": "solarized:base02", "attrs": [] },
"gitstatus_changed":         { "fg": "solarized:orange",  "bg": "solarized:base02", "attrs": [] },
"gitstatus_untracked":       { "fg": "solarized:yellow",  "bg": "solarized:base02", "attrs": [] },
"gitstatus_stashed":         { "fg": "solarized:blue",    "bg": "solarized:base02", "attrs": [] },
"gitstatus:divider":         { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] }
```

If this doesn't solve your problem, please enable the Powerline log and see if it contains a hint.

PS: I'm gonna work on #3 soon, so if the log currently doesn't point to something, hopefully it will when #3 is resolved.

**Comment by jaspernbrouwer** [comment]
Issue #3 has been addressed, some logging has been added. Please enable logging with log-level `DEBUG`.

PS: No tag/release includes logging yet, so you'll need to download/clone the latest code manually.

**Comment by jaspernbrouwer** [comment]
@TimeTravelersHackMe: Please upgrade to [v1.1.0](https://github.com/jaspernbrouwer/powerline-gitstatus/releases/tag/v1.1.0), it includes logging and some other fixes.

**Comment by jaspernbrouwer** [comment]
Closing due to lack of feedback.

**Comment by 0ric1** [comment]
> Looks like my segment is used in the shell theme `default_leftonly` and some (or all) highlight groups from my segment are not present in the color-scheme `solarized`.
> 
> If you're not using the color-scheme `solarized`, this is not the source of you issue. In any case, you can add this to the `groups` section of `.config/powerline/colorschemes/solarized.json`:
> 
> ```json
> "gitstatus":                 { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] },
> "gitstatus_branch":          { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] },
> "gitstatus_branch_clean":    { "fg": "solarized:green",   "bg": "solarized:base02", "attrs": [] },
> "gitstatus_branch_dirty":    { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] },
> "gitstatus_branch_detached": { "fg": "solarized:magenta", "bg": "solarized:base02", "attrs": [] },
> "gitstatus_behind":          { "fg": "solarized:base2",   "bg": "solarized:base02", "attrs": [] },
> "gitstatus_ahead":           { "fg": "solarized:base2",   "bg": "solarized:base02", "attrs": [] },
> "gitstatus_staged":          { "fg": "solarized:green",   "bg": "solarized:base02", "attrs": [] },
> "gitstatus_unmerged":        { "fg": "solarized:red",     "bg": "solarized:base02", "attrs": [] },
> "gitstatus_changed":         { "fg": "solarized:orange",  "bg": "solarized:base02", "attrs": [] },
> "gitstatus_untracked":       { "fg": "solarized:yellow",  "bg": "solarized:base02", "attrs": [] },
> "gitstatus_stashed":         { "fg": "solarized:blue",    "bg": "solarized:base02", "attrs": [] },
> "gitstatus:divider":         { "fg": "solarized:base1",   "bg": "solarized:base02", "attrs": [] }
> ```
> 
> If this doesn't solve your problem, please enable the Powerline log and see if it contains a hint.
> 
> PS: I'm gonna work on #3 soon, so if the log currently doesn't point to something, hopefully it will when #3 is resolved.

`"gitstatus_tag":             { "fg": "darkcyan",        "bg": "gray2", "attrs": [] },` is missing in the list.

**Comment by 0ric1** [comment]
To make `powerline-lint` happy you need to add it to `default.json` too.

**Comment by jeshwanth-harish** [comment]
How was the following fixed??
powerline-lint

Error while checking theme (key /segments/left/list item 6/function)
  in "/Users/jessyharish/.config/powerline/themes/shell/default.json", line 28, column 40:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^
found highlight group gitstatus:divider not defined in the following colorschemes: default, solarized
(Group name was obtained from function documentation.)
  in "<gitstatus docstring>", line 27, column 34:
    Divider highlight group used: ``gitstatus:divider``.
                                    ^

Error while checking theme (key /segments/left/list item 6/function)
found highlight groups list (gitstatus_branch_detached) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/jessyharish/.config/powerline/themes/shell/default.json", line 28, column 40:
     ... function": "powerline_gitstatus.gitstatus",
                                         ^

Error while checking theme (key /segments/left/list item 6/function)
found highlight group gitstatus_branch_detached not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/left/list item 6/function)
found highlight groups list (gitstatus_branch_dirty) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/jessyharish/.config/powerline/themes/shell/default.json", line 28, column 40:
     ... function": "powerline_gitstatus.gitstatus",
